### ISSUE TITLE
Twilight UI Preset remains even after Twilight UI is uninstalled.

### ISSUE THREAD

**Issue by XtraButtery** [mouse0270/lib-themer#8] opened 2021-09-23 14:36 UTC
If the Twilight UI Preset was set when the Twilight UI module is uninstalled it will remain in the list even after it is deselected and the game is restarted.
![image](https://user-images.githubusercontent.com/35461692/134526857-4c472d32-2085-443b-b57b-0c4cabd151d1.png)

**Comment by mouse0270** [comment] 2021-09-23 15:23
This might be fixed in a new version I have updated. I will double check.

The problem is I was using foundrys `mergeObject` function for this and while, it is bugged and doesn't work with blank objects and always merges them. So it was keeping ghost elements.

I reported this and rewrote it, but I am not sure if I have pushed that version. I recently had a major life event upset my time and really just getting back into everything as of a week ago.

I will verify this and see if I can push out the udpated code that should handle this but no real promises until I can look at it later today or tomorrow.

**Comment by XtraButtery** [comment] 2021-09-23 16:05
Sorry to hear about your personal issues, I wish you all the best.

Despite my massive influx of bug reports, I'm a real big fan of the module and what it does. If you'd like any help testing out new code or features at any point, feel free to let me know as I've honestly had a lot of fun trying to uncover all the various issues lately.

**Comment by mouse0270** [comment] 2021-09-23 16:07
Life happens and its not always great. Thank you for your kind words.

No no no, I've been waiting for a big list of bugs, Its kinda hard as someone who uses foundry for my very basic needs to know what this module breaks on. I really dont use more then like 20% of what foundry has to offer (I recently learned it can do camera's and VC). So I need lots of bug reports to be able to fix things. Thank you for taking your time to break this module, I do appricate it.

**Comment by mouse0270** [comment] 2022-10-23 23:21
Closing this as I don't believe this is valid for the current implementation of libThemer.

**Closed by mouse0270** 2022-10-23 23:21 UTC
Labels: bug
