### ISSUE TITLE
Options to configure Tidy UI Settings and Tidy5e Sheet Settings are present even when modules are not installed or disabled.

### ISSUE THREAD

**Issue by XtraButtery** [mouse0270/lib-themer#10] opened 2021-09-23 16:59 UTC
As stated in the title, the settings tabs for Tidy UI and Tidy5e Sheet are always present even if neither module is installed or both modules are disabled.

This leads to redundant settings which could confuse a user if nothing is changing when they alter the settings as a new user could believe that Tidy UI and Tidy5e Sheet are simply settings within Lib Themer rather than independent modules

If the usage of these additional modules is recommended, but not a dependency of Lib Themer to function, adding in a check for these modules and adding in a bit of text to warn the user that the modules are not present when viewing their settings would improve user functionality.

**Comment by mouse0270** [comment] 2021-09-24 12:04
Currently this is working as intended. Unlike other theming options I do not plan on adding checks for modules or versions. 

They way I see it, if you enable it and don't like it, its just as easy to disable. Currently marked as `wontfix` may come back and change this later.

**Comment by mouse0270** [comment] 2022-09-15 01:27
Fixed in v0.1.0b for Foundry v10.

Current beta found: https://github.com/mouse0270/lib-themer/releases/download/0.1.0b/module.json

**Comment by mouse0270** [comment] 2022-09-15 01:28
To include more information themes now have a `requires` property that can be set to require specific modules or systems to be loaded

**Closed by mouse0270** 2022-09-15 01:27 UTC
Labels: enhancement, wontfix
